In [48]:
import pandas as pd
coffee=pd.read_csv('./complete-pandas-tutorial/warmup-data/coffee.csv')

In [6]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [12]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [20]:
coffee.sample(10, random_state=1)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [8]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [4]:
results =pd.read_parquet('./complete-pandas-tutorial/data/results.parquet')
results

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [5]:
olympics_data = pd.read_excel('./complete-pandas-tutorial/data/olympics-data.xlsx')

In [9]:
bios=pd.read_csv('./complete-pandas-tutorial/data/bios.csv')
bios.to_excel
bios.to_parquet

<bound method DataFrame.to_parquet of         athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux
1                2         Arnaud Boetsch  1969-04-01           Meulan
2                3           Jean Borotra  1898-08-13         Biarritz
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe
4                5           Albert Canet  1878-04-17       Wandsworth
...            ...                    ...         ...              ...
145495      149222      Polina Luchnikova  2002-01-30            Serov
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas
145498      149225         André Foussard  1899-05-19            Niort
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN
1                   Yvelines          FRA     France      183.0       76.0
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0
3                      Paris          FRA     France      168.0       64.0
4                    England          GBR     France        NaN        NaN
...                      ...          ...        ...        ...        ...
145495            Sverdlovsk          RUS        ROC      167.0       61.0
145496                Moskva          RUS        ROC      168.0       65.0
145497           Arkhangelsk          RUS        ROC      163.0       55.0
145498           Deux-Sèvres          FRA     France      166.0        NaN
145499       New South Wales          AUS  Australia        NaN        NaN

         died_date
0       1960-10-02
1              NaN
2       1994-07-17
3       1978-03-20
4       1930-07-25
...            ...
145495         NaN
145496         NaN
145497         NaN
145498  1986-03-18
145499  2003-10-20

[145500 rows x 10 columns]>

In [26]:
coffee.loc[[1,2,4]]

         Day Coffee Type  Units Sold
1     Monday       Latte          15
2    Tuesday    Espresso          30
4  Wednesday    Espresso          35

In [29]:
coffee.loc[0:3]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [38]:
coffee.loc[0:3,["Day","Units Sold"]]

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30
3  Tuesday          20

In [49]:
coffee.iloc[0:3,[0,2]]

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30

In [53]:
coffee.loc[1,"Units Sold"] =95
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          95
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [55]:
coffee.iloc[0,2] =75
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          75
1      Monday       Latte          95
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [59]:
coffee["Coffee Type"]

0     Espresso
1        Latte
2     Espresso
3        Latte
4     Espresso
5        Latte
6     Espresso
7        Latte
8     Espresso
9        Latte
10    Espresso
11       Latte
12    Espresso
13       Latte
Name: Coffee Type, dtype: str

In [43]:
coffee.index=coffee["Day"]

In [60]:
coffee.loc["Monday":"Saturday"]

Empty DataFrame
Columns: [Day, Coffee Type, Units Sold]
Index: []

In [64]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [67]:
coffee.sort_values("Units Sold",ascending=True)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
13     Sunday       Latte          35
11   Saturday       Latte          35
9      Friday       Latte          35
6    Thursday    Espresso          40
12     Sunday    Espresso          45
10   Saturday    Espresso          45
8      Friday    Espresso          45
0      Monday    Espresso          75
1      Monday       Latte          95

In [71]:
coffee.sort_values(["Units Sold","Coffee Type"],ascending=True)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
0      Monday    Espresso          75
1      Monday       Latte          95

In [75]:
coffee.sort_values(["Units Sold","Coffee Type"],ascending=[1,0])

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
2     Tuesday    Espresso          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
0      Monday    Espresso          75
1      Monday       Latte          95

In [76]:
for index,row in coffee.iterrows():
    print(index)
    print(row)

0
Day              Monday
Coffee Type    Espresso
Units Sold           75
Name: 0, dtype: object
1
Day            Monday
Coffee Type     Latte
Units Sold         95
Name: 1, dtype: object
2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object
3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object
4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object
5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object
6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object
7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object
8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object
9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object
10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object
11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object
12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object
13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object